apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: preference
      version: v1
    name: s2i-java
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: fabric8/s2i-java
      from:
        kind: DockerImage
        name: fabric8/s2i-java
      generation: null
      importPolicy: {}
      name: latest
      referencePolicy:
        type: ""
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: preference
      version: v1
    name: preference-v1
  spec: {}
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: preference
      version: v1
    name: preference-v1
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: preference-v1:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: preference/java/springboot
      git:
        uri: https://github.com/alancruzm14/istioTutorial
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-java:latest
      type: Source
    triggers:
    - github:
        secret: MevYjglcei_L8VBMniRY
      type: GitHub
    - generic:
        secret: dYd_KjycXGjln8Q1xh0J
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: preference
      version: v1
    name: preference-v1
  spec:
    replicas: 1
    selector:
      app: preference
      deploymentconfig: preference-v1
      version: v1
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: preference
          deploymentconfig: preference-v1
          version: v1
      spec:
        containers:
        - env:
          - name: JAVA_OPTIONS
            value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true
          image: yanelike/preference:latest
          name: preference-v1
          ports:
          - containerPort: 9779
            protocol: TCP
          - containerPort: 8778
            protocol: TCP
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - preference-v1
        from:
          kind: ImageStreamTag
          name: preference-v1:latest
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: preference
      version: v1
    name: preference-v1
  spec:
    ports:
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
    - name: 9779-tcp
      port: 9779
      protocol: TCP
      targetPort: 9779
    selector:
      app: preference
      deploymentconfig: preference-v1
      version: v1
  status:
    loadBalancer: {}
kind: List
metadata: {}
